# Heart Statistics

##### This document demonstrates how the author of the GMB bot simulated the random and pseudo-consistency of the heart strings.

In [3]:
import numpy

In [29]:
N = [133, 118, 188, 213, 221]
L = [195, 161, 240, 213, 232]

mean_N = numpy.mean(N)
mean_L = numpy.mean(L)

max_N = numpy.max(N)
max_L = numpy.max(L)

min_N = numpy.min(N)
min_L = numpy.min(L)

std_N = numpy.std(N)
std_L = numpy.std(L)

print(f"Mean\nN: {mean_N}, L: {mean_L}")
print(f"Max\nN: {max_N}, L: {max_L}")
print(f"Min\nN: {min_N}, L: {min_L}")
print(f"Std\nN: {round(float(std_nN,1)}, L: {round(float(std_L),1)}")

Mean
N: 174.6, L: 208.2
Max
N: 221, L: 240
Min
N: 118, L: 161
Std
N: 41.8, L: 28.3


#### We can deduce that L sends more hearts so we'll use his statistics to form the normal distribution.

### Generating random normal dsitr.

We create a Gaussian Distribution to create a mid point of 208.2 (mean_L) with max deviations from the left and right of 41.8 (std_N)

In [ ]:
x = numpy.random.normal(208.2, 41.8,1000)
print(int(numpy.random.choice(x)))

: 